# Generated by Django 2.1.2 on 2019-05-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_auto_20190510_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rut',
        ),
        migrations.AddField(
            model_name='perfil',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
